Log:
  Level: debug # Log level: none, error, warning, info, debug 
  AccessPath: # ./access.Log
  ErrorPath: # ./error.log
DnsConfigPath: # ./dns.json Path to dns config 
Nodes:
  -
    PanelType: "V2board" # Panel type: SSpanel, V2board
    ApiConfig:
      ApiHost: "https://vadmin.online" # 修改这里
      ApiKey: "0xMDllZGNmN2MxODhAY2YtY" # 修改这里
      NodeID: 1
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type, Remote configuration first
      EnableXTLS: false # Enable XTLS for V2ray and Trojan, emote configuration first
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/ssl/private/fullchain.pem # Provided if the CertMode is file
        KeyFile: /etc/ssl/private/privkey.pem
        Provider: cloudflare 
        Email: walletha.com@gmail.com
        DNSEnv:   # DNS ENV option used by DNS provider
          CLOUDFLARE_EMAIL: walletha.com@gmail.com
          CLOUDFLARE_API_KEY: dbd4889d0aa90c99c5f3cb639828ea7be3a0a
